---
- name: Install arch linux workstation apps
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: install C/C++ development tools
    pacman:
      name:
        - base-devel
        - cmake
        - premake
        - gdb
        - valgrind
    become: true
  - name: Create aur_builder user
    user:
      name: aur_builder
      group: wheel
  - name: add aur_builder to passwordless sudoers
    lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'
  - name: install snapd from aur
    aur:
      name: snapd
    become: yes
    become_user: aur_builder
  - name: Install htop
    pacman:
      name: htop
      state: present
    tags: base
  - name: Make sure snap is enabled and not masked
    systemd:
      name: snapd.socket
      enabled: yes
      masked: no
    tags: snap
  - name: Make sure a service is running
    systemd:
      state: started
      name: snapd.socket
    tags: snap
  - name: Create symlink snapd service
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      state: link
    tags: snap
  - name: Execute task with extended PATH
    lineinfile:
      path: /etc/profile
      line: "export PATH=$PATH:/snap/bin/"
      state: present
    tags: snap
  - name: source /etc/profile
    shell: source /etc/profile
    tags: snap
  - name: Install neovim
    pacman:
      name: neovim
      state: present
    tags: vim
  - name: Install python-neovim
    pacman:
      name: python-neovim
      state: present
    tags: vim
  - name: Install fish
    pacman:
      name: fish
      state: present
    tags: cli
  - name: Install tmux
    pacman:
      name: tmux
      state: present
    tags: cli

  - name: Install KeePassXC pw mgr with --channel=latest/edge
    snap:
      name: keepassxc
      channel: latest/edge
    tags: security

  - name: Install Chromium web browser with --channel=latest/edge
    snap:
      name: chromium
      channel: latest/edge
    tags: webbrowsers

  - name: Install vs code with --channel=latest/edge
    snap:
      name: code
      channel: latest/stable
      classic: yes
    tags: vscode

  - name: Install qutebrowser
    pacman:
      name: qutebrowser
      state: present
    tags: webbrowsers

  - name: Install PCmanFM
    pacman:
      name: pcmanfm
      state: present
    tags: filemanagers
  - name: Install weechat
    pacman:
      name: weechat
      state: present
    tags: chat
  - name: Create directory for minpac neovim
    file:
      path: /home/llm1n01/.config/nvim/pack/minpac/opt
      state: directory
    tags: vim
  - name: Checkout minpac repo
    git:
      repo: 'https://github.com/k-takata/minpac.git'
      dest: /home/llm1n01/.config/nvim/pack/minpac/opt/minpac
    tags: vim
  - name: Install VirtualBox
    pacman:
      name: virtualbox
      state: present
    tags: virtualbox
  #- name: Install virtualbox-host-modules-arch
    # pacman:
      #  name: virtualbox-host-modules-arch
      # state: present
    # tags: virtualbox
  - name: Install linux headers
    pacman:
      name: linux-headers
      state: present
    tags: virtualbox
  - name: install Docker
    pacman:
      name: docker
    become: true

  - name: configure Docker user namespace remap range
    copy:
      dest: /etc/subuid
      content: |
        default:165536:4096
      mode: 0644
    become: true

  - name: configure Docker group namespace remap range
    copy:
      dest: /etc/subgid
      content: |
        default:165536:4096
      mode: 0644
    become: true

  - name: create /etc/docker directory
    file:
      path: /etc/docker
      state: directory
      owner: root
      group: root
      mode: 0755
    become: true

  - name: configure Docker daemon
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      mode: 0644
    become: true

  - name: start Docker daemon
    systemd:
      name: docker.service
      state: started
      enabled: true
    become: true











