---
- name: Install arch linux workstation apps
  hosts: localhost
  connection: local
  become: true
  tasks: 
  - name: Install htop
    pacman:
      name: htop
      state: present
    tags: base
  - name: Install neovim
    pacman: 
      name: neovim
      state: present
    tags: vim
  - name: Install python-neovim
    pacman: 
      name: python-neovim
      state: present
    tags: vim
  - name: Install fish
    pacman: 
      name: fish
      state: present
    tags: cli 
  - name: Install tmux
    pacman: 
      name: tmux
      state: present
    tags: cli
  - name: Install powerline 
    pacman: 
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - powerline        
    tags: cli
  - name: Install tmux
    pacman: 
      name: tmux
      state: present
    tags: cli
  - name: Install tmux
    pacman: 
      name: tmux
      state: present
    tags: cli
  - name: Install Brave web browser with --channel=latest/edge
    snap:
      name: brave
      channel: latest/edge
    tags: webbrowsers

  - name: Install KeePassXC pw mgr with --channel=latest/edge
    snap:
      name: keepassxc
      channel: latest/edge
    tags: security

  - name: Install Chromium web browser with --channel=latest/edge
    snap:
      name: chromium
      channel: latest/edge
    tags: webbrowsers

  - name: Install qutebrowser
    apt:
      name: qutebrowser
      state: present
    tags: webbrowsers

  - name: Install PCmanFM
    apt:
      name: pcmanfm
      state: present
    tags: filemanagers

  - name: Install arandr
    apt:
      name: arandr
      state: present
    tags: display     
       
       
       

