theme = "modern"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias =  " "
info_type = "available"
unit = "GB"
interval = 20
warning = 5.0
alert = 2.0

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
